config/routes.rb
Store::Application.routes.draw do
  resources :product_types

  resources :products

   root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_type
	serialize :properties, Hash
	validate :validate_properties

	def validate_properties
		product_type.fields.each do |field|
			if field.required? && properties[field.name].blank?
				errors.add field.name, "must not be blank"
			end
		end	
	end
end

app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :product_type
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
	has_many :fields, class_name: "ProductField"
	accepts_nested_attributes_for :fields, allow_destroy: true
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
    @product_type.fields.build
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)
    @product_type.fields.build

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      #params.require(:product_type).permit(:name, :fields_attributes)
      params.require(:product_type).permit!
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
def new
  @product = Product.new(product_type_id: params[:product_type_id])
end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_types/_field_fields.html.erb
<fieldset>
  <%= f.select :field_type, %w[text_field check_box] %>
  <%= f.text_field :name, placeholder: "field_name " %>
  <%= f.check_box :required %> <%= f.label :required %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "[remove]", '#', class: "remove_fields" %>
</fieldset>

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :fields do |builder| %>
    <%= render 'field_fields', f:builder %>
  <% end %>
  <%= link_to_add_fields "Add Field", f , :fields %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing product_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<h1>Listing product_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.name %></td>
        <td><%= link_to 'Show', product_type %></td>
        <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
        <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New product_type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_type.name %>
</p>

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :product_type_id %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <%= f.fields_for :properties, OpenStruct.new(@product.properties) do |builder|%>
    <% @product.product_type.fields.each do |field| %>
      <% unless field.field_type.blank?%>
        <%= render "products/fields/#{field.field_type}", field: field, f:builder %>
      <% end %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/fields/_check_box.html.erb
<div class="field">
  <%= f.check_box field.name %>
  <%= f.label field.name %>
</div>

app/views/products/fields/_text_field.html.erb
<div class="field">
  <%= f.label field.name %><br />
  <%= f.text_field field.name %>
</div>

app/views/products/index.html.erb
<h1>Store</h1>

<%if @products.empty? %>
  <p><strong>No products</strong></p>
<% end %>

<% @products.each do |product| %>
  <div class="product">
    <h2><%= product.name %></h2>
    Price: <%= number_to_currency(product.price) %>
  </div>
<% end %>

<%= form_tag new_product_path, method: :get do %>
  <%= select_tag :product_type_id, options_from_collection_for_select(ProductType.all, :id, :name) %>
  <%= submit_tag "New Product", name: nil %>

<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<% @product.properties.each do |name, value| %>
	<p>
		<b> <%= name.humanize %> :</b>
		<%=value%>

	</p>

<% end %>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>